[theme]
base="light"
primaryColor="0055b3"

[server]
enableXsrfProtection = false  # (Optional) Disable XSRF protection
enableCORS = false  # (Optional) Disable CORS

[client]
showSidebarNavigation = false